#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
apply_merge.py — 中心合入判定后的「落盘」脚本（Phase 1 · §6）

承接 merge_candidates.py 产出的 merged_review.json：对 verdict=="merge" 的目标，
读取其 adaptation_manifest.json 指向的 adapted_skill_path（子 Agent 真实跑出的适配产物，
即一份完整 SKILL.md 文本），生成「独立变体」SKILL.md。

安全第一（延续方法学 §6「中心只认文件、不认嘴」的边界）：
  - 默认：仅把草稿写入 skill/adaptations/_merged/<target>.md，**绝不覆盖**线上主 skill
          或子 Agent 目录；草稿可人工审阅后手动落盘。
  - --apply：把草稿提升（promote）到 skill/adaptations/<target>/SKILL.md（子 Agent 自有目录，
          属于「执行结果可入仓库」产物）。
  - --apply-main --target X：把 X 的变体覆盖到主 skill/SKILL.md（覆盖前自动备份为 .bak.<时间戳>）。
          这是唯一会改动主 skill 的路径，必须显式开启且指定目标。

与 merge_candidates.py 的分工：
  merge_candidates 只「判定」（读文件、出 merged_review.json），不写任何产物；
  apply_merge 只「落盘」（依据判定结果生成/提升变体），不重新做红队/棘轮判定。
  两者可串成：merge_candidates --root ... --out merged_review.json && apply_merge --review merged_review.json --root ...

零依赖：仅标准库。不触达 OpenAI SDK / 不需要 OPENAI_API_KEY。
"""

import argparse
import datetime
import json
import shutil
import sys
import tempfile
from pathlib import Path

import merge_candidates as mc  # 复用 load_manifests / decide_merge


# ---------------------------------------------------------------------------
# 1. 工具：manifest 索引 + 适配体解析
# ---------------------------------------------------------------------------
def manifest_map(root):
    """{target: manifest}，复用 merge_candidates 的容错读取。"""
    return {m.get("target"): m for m in mc.load_manifests(root)}


def resolve_adapted_path(root, manifest):
    """解析 manifest.adapted_skill_path → 存在的 Path，否则 None。

    真实 run_loop 写出的是相对仓库根的 path；这里依次尝试：
      1) 原样（绝对或相对 CWD）
      2) root 的父目录（即仓库根）拼接
    """
    raw = manifest.get("adapted_skill_path", "")
    if not raw:
        return None
    candidates = [Path(raw), Path(root).parent / raw]
    for p in candidates:
        if p.exists():
            return p
    return None


def _strip_frontmatter(text):
    """去掉首部 YAML frontmatter（--- ... ---），避免变体出现双重 frontmatter。"""
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            return text[end + 4:].lstrip("\n")
    return text


# ---------------------------------------------------------------------------
# 2. 生成独立变体（纯函数，可单测）
# ---------------------------------------------------------------------------
def build_variant(target, manifest, adapted_body, ratchet_delta):
    """由适配体 + manifest 元数据，拼出一份可加载的独立变体 SKILL.md 文本。"""
    src = manifest.get("adapted_skill_path", "")
    body = _strip_frontmatter(adapted_body)
    provenance = (
        "\n\n---\n\n"
        "## Provenance & Integrity\n\n"
        f"- Generated by `scripts/apply_merge.py` from a `merge` verdict in `merged_review.json`.\n"
        f"- Target model: **{target}**\n"
        f"- Best score: {manifest.get('best_score')} ｜ Ratchet delta: {ratchet_delta}\n"
        f"- Source manifest: `{target}/adaptation_manifest.json` (adapted_skill_path: `{src}`)\n"
        "- Red-team gate: **PASS** (inherited from the merge decision).\n"
        "- This variant MUST inherit all Safety & Integrity Constraints from the base skill; "
        "it must not remove them.\n"
    )
    return (
        "---\n"
        f"name: prompt-model-adaptation-{target}\n"
        f"description: {target}-adapted variant of prompt-model-adaptation. "
        f"Portable system-prompt skill tuned for the {target} family; "
        f"inherits the base workflow and safety constraints.\n"
        "---\n\n"
        f"# Prompt Model Adaptation — {target} variant\n\n"
        "> Auto-generated by `scripts/apply_merge.py`. The Provenance section is authoritative for audit.\n\n"
        f"{body}"
        f"{provenance}"
    )


def collect_applies(review):
    """从 merged_review.json 取出 verdict=='merge' 的判定。"""
    return [d for d in review.get("decisions", []) if d.get("verdict") == "merge"]


# ---------------------------------------------------------------------------
# 3. 落盘主流程
# ---------------------------------------------------------------------------
def apply_merge(review_path, root, out_dir, do_apply=False,
                do_main=False, main_target=None):
    """按 merged_review.json 把合入目标落盘为独立变体。

    返回已落盘草稿的 [(target, variant_text), ...]。
    """
    review = json.loads(Path(review_path).read_text(encoding="utf-8"))
    ms = manifest_map(root)
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    applied = []

    for d in collect_applies(review):
        target = d["target"]
        m = ms.get(target)
        if not m:
            print(f"⚠ 找不到 {target} 的 manifest，跳过", file=sys.stderr)
            continue
        adapted_path = resolve_adapted_path(root, m)
        if not adapted_path:
            print(f"⚠ {target} 的适配产物缺失（{m.get('adapted_skill_path')}），跳过",
                  file=sys.stderr)
            continue
        body = adapted_path.read_text(encoding="utf-8")
        variant = build_variant(target, m, body, d.get("ratchet_delta"))

        draft = out_dir / f"{target}.md"
        draft.write_text(variant, encoding="utf-8")
        print(f"  ✓ 草稿: {draft}")
        applied.append((target, variant))

        if do_apply:
            dest = Path(root) / target / "SKILL.md"
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(variant, encoding="utf-8")
            print(f"  ✓ 提升: {dest}")

    if do_main:
        if not main_target:
            print("⚠ --apply-main 需配合 --target <name>", file=sys.stderr)
        else:
            draft = out_dir / f"{main_target}.md"
            if not draft.exists():
                print(f"⚠ 无 {main_target} 草稿可提升为主 skill", file=sys.stderr)
            else:
                main_skill = Path(root).parent / "SKILL.md"  # root=skill/adaptations → 父=skill
                if main_skill.exists():
                    ts = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
                    bak = main_skill.with_name(f"SKILL.md.bak.{ts}")
                    shutil.copy2(main_skill, bak)
                    print(f"  ⓘ 已备份主 skill: {bak}")
                main_skill.write_text(draft.read_text(encoding="utf-8"), encoding="utf-8")
                print(f"  ✓ 主 skill 已更新: {main_skill}")

    return applied


# ---------------------------------------------------------------------------
# 4. 离线演示
# ---------------------------------------------------------------------------
def _demo():
    tmp = Path(tempfile.mkdtemp(prefix="apply_demo_"))
    root = tmp / "adaptations"
    baseline = {"gemini": 0.70, "claude": 0.65}

    # gemini：merge（红队过 + 棘轮正向）
    gdir = root / "gemini"
    gdir.mkdir(parents=True)
    (gdir / "adapted.SKILL.md").write_text(
        "---\nname: base\ndescription: x\n---\n# Base\nSystem prompt for gemini.\n",
        encoding="utf-8")
    (gdir / "adaptation_manifest.json").write_text(
        json.dumps({
            "target": "gemini", "best_score": 0.9, "redteam_violations": [],
            "redteam_gate_pass": True,
            "adapted_skill_path": "adaptations/gemini/adapted.SKILL.md",
        }, ensure_ascii=False), encoding="utf-8")

    # claude：revert（红队挂）→ 不应生成草稿
    cdir = root / "claude"
    cdir.mkdir(parents=True)
    (cdir / "adapted.SKILL.md").write_text("# Base claude\n", encoding="utf-8")
    (cdir / "adaptation_manifest.json").write_text(
        json.dumps({
            "target": "claude", "best_score": 0.9, "redteam_violations": ["RT-03"],
            "redteam_gate_pass": False,
            "adapted_skill_path": "adaptations/claude/adapted.SKILL.md",
        }, ensure_ascii=False), encoding="utf-8")

    review = mc.merge_candidates(root, baseline, root / "merged_review.json")
    out = tmp / "_merged"
    applied = apply_merge(root / "merged_review.json", root, out)
    print(f"\n(演示草稿目录: {out})")
    print(f"(应仅 gemini 落盘，claude 因 revert 跳过：{[t for t, _ in applied]})")
    return applied


# ---------------------------------------------------------------------------
# 5. CLI
# ---------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser(description="中心合入判定后的落盘脚本（离线）")
    ap.add_argument("--review", help="merged_review.json 路径（来自 merge_candidates.py）")
    ap.add_argument("--root",
                    help="adaptations 工作区根目录（含 */adaptation_manifest.json）")
    ap.add_argument("--out", help="草稿输出目录（默认 skill/adaptations/_merged）")
    ap.add_argument("--apply", action="store_true",
                    help="把草稿提升（promote）到 skill/adaptations/<target>/SKILL.md")
    ap.add_argument("--apply-main", action="store_true",
                    help="把某目标变体覆盖主 skill/SKILL.md（覆盖前自动备份，需 --target）")
    ap.add_argument("--target", help="--apply-main 指定的目标模型名")
    ap.add_argument("--demo", action="store_true", help="离线演示：合成 1 merge + 1 revert 跑一遍")
    args = ap.parse_args()

    if args.demo:
        _demo()
        return

    if not args.demo and not args.root:
        ap.error("需 --root（--demo 模式除外）")
    if not args.review:
        ap.error("需 --review 或 --demo")
    out_dir = args.out or str(Path(args.root) / "_merged")
    apply_merge(args.review, args.root, out_dir,
                do_apply=args.apply, do_main=args.apply_main, main_target=args.target)


if __name__ == "__main__":
    main()
